/**
 * Centralized Application Constants
 * Prevents magic numbers and magic strings throughout the backend routing layers.
 */

const HTTP_STATUS = {
  OK: 200,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  INTERNAL_ERROR: 500,
};

const PAGINATION = {
  DEFAULT_LIMIT: 50,
  MAX_LIMIT: 200,
  DEFAULT_OFFSET: 0,
};

const SOCIAL_BATTERY = {
  MIN: 0,
  MAX: 100,
  CRITICAL_THRESHOLD: 20,
  DEFAULT_HRV: 50,
  HRV_MIN_BASELINE: 20,
  DEFAULT_SLEEP: 50,
  HRV_WEIGHT: 0.6,
  SLEEP_WEIGHT: 0.4,
};

const TIMERS = {
  SSE_HEARTBEAT_MS: 25000,
};

const TRUST_LAYERS = {
  INNER_CIRCLE: 'INNER_CIRCLE',
  EXTENDED_POLYCULE: 'EXTENDED_POLYCULE',
  OUTER_RING: 'OUTER_RING',
  FRIENDS_OF_FRIENDS: 'FRIENDS_OF_FRIENDS',
};
const TRUST_LAYER_HIERARCHY = [
  TRUST_LAYERS.INNER_CIRCLE,
  TRUST_LAYERS.EXTENDED_POLYCULE,
  TRUST_LAYERS.OUTER_RING,
  TRUST_LAYERS.FRIENDS_OF_FRIENDS,
];

module.exports = {
  HTTP_STATUS,
  PAGINATION,
  SOCIAL_BATTERY,
  TIMERS,
  TRUST_LAYERS,
  TRUST_LAYER_HIERARCHY,
};
